version: 1.0.{build}
build: off
notifications:
- provider: Webhook
  url: https://webhooks.gitter.im/e/da9968361f04e8da6bbc
  method: POST
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
